import { configApp } from '@adonisjs/eslint-config'

export default [
  ...configApp(),

  /**
   * database/schema.ts is regenerated by "node ace migration:run" and is
   * marked DO NOT EDIT. The generator's output is not prettier-conformant,
   * so linting it only produces errors that come back on the next run.
   */
  { ignores: ['database/schema.ts'] },
]
